[project]
name = "trp1-chimera-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yonas Mekonnen", email = "myonas886@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
trp1-chimera-ai = "trp1_chimera_ai:main"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
